#!/usr/bin/env python3
"""
make_table.py — build a blank metadata table from an ENA sample checklist.

Run this once, before biosamples.py, whenever you switch to a checklist you
have no template for:

    1. Download your checklist XML from
       https://www.ebi.ac.uk/ena/browser/checklists
    2. Point the 'checklist' key of config.yaml at that file, and
       'data_biosamples' at the table you want to create.
    3. python make_table.py
    4. Fill the DATA sheet in with your samples.
    5. python biosamples.py

The generated table has one column per checklist field, plus the three
columns every ENA submission needs regardless of checklist (isolate,
organism, taxon_id). Fields that take a unit get a companion
"<field> [unit]" column. The INFO sheet documents every field in the
checklist, including the optional ones left out of the DATA sheet.

This script only ever writes a template. It never contacts ENA and never
touches an existing submission.
"""

import argparse
import os
import sys

# Reuse the checklist parser from biosamples.py so both scripts always agree
# on how a checklist is read.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from biosamples import (  # noqa: E402
    CORE_COLUMNS,
    load_config,
    parse_checklist,
    _norm,
)

# Short descriptions for the three non-checklist columns
CORE_HELP = {
    "isolate": "Your own unique identifier for the sample. Becomes the ENA "
               "sample alias, so it must be unique within your Webin account.",
    "organism": "Scientific name of the organism. Becomes the sample title.",
    "taxon_id": "NCBI taxonomy identifier, check it at "
                "https://www.ncbi.nlm.nih.gov/taxonomy",
}

INFO_HEADER = ["Field name", "Status", "Units", "Allowed values",
               "Description", "Field group", "ENA field name"]

MAX_CHOICES_SHOWN = 12

# Colours for the DATA header, by status
FILL_BY_STATUS = {
    "core":        "C6E0B4",   # green
    "mandatory":   "FFD966",   # amber
    "recommended": "DDEBF7",   # pale blue
    "optional":    "F2F2F2",   # grey
    "unit":        "EDEDED",   # lighter grey
}


def summarise_choices(choices) -> str:
    """Render a controlled vocabulary compactly, some run to 294 values."""
    if not choices:
        return ""
    if len(choices) <= MAX_CHOICES_SHOWN:
        return "; ".join(choices)
    shown = "; ".join(choices[:MAX_CHOICES_SHOWN])
    return f"{shown}; ... ({len(choices)} values in total, see the checklist XML)"


def select_fields(spec, all_fields=False, extra_mandatory=None):
    """
    Decide which checklist fields become columns.

    By default: mandatory and recommended fields. With all_fields, every
    optional field too. Entries of 'extra_mandatory' that are not checklist
    fields are appended so the table matches what biosamples.py will demand.

    Returns a list of (column name, status, units) tuples, core columns first.
    """
    wanted = {"mandatory", "recommended"}
    if all_fields:
        wanted.add("optional")

    columns = [(name, "core", []) for name in CORE_COLUMNS]

    for key in spec["order"]:
        field = spec["fields"][key]
        if field["status"] in wanted:
            columns.append((field["label"], field["status"], field["units"]))

    # Group mandatory fields together at the front, keeping checklist order
    # within each group. Easier to fill in, and blank mandatory cells are the
    # only thing that will stop a submission.
    rank = {"core": 0, "mandatory": 1, "recommended": 2, "optional": 3}
    columns.sort(key=lambda item: rank[item[1]])

    # Fields the config marks mandatory are shown as mandatory even when the
    # checklist calls them optional, otherwise the same config would colour a
    # column differently depending on whether --all-fields was passed.
    required = {_norm(entry) for entry in (extra_mandatory or [])}
    columns = [(name, "mandatory" if _norm(name) in required else status, units)
               for name, status, units in columns]

    known = {_norm(name) for name, _, _ in columns}
    for entry in (extra_mandatory or []):
        if _norm(entry) not in known:
            columns.append((str(entry).strip(), "mandatory", []))
            known.add(_norm(entry))

    return columns


def build_info_rows(spec, columns):
    """One row per checklist field, plus a preamble explaining the table."""
    in_table = {_norm(name) for name, _, _ in columns}

    rows = [
        [f"Template for ENA checklist {spec['accession']} ({spec['name']})", "", "", "", "", "", ""],
        ["Generated by ENflorA make_table.py. Fill in the DATA sheet, one row per sample.", "", "", "", "", "", ""],
        ["", "", "", "", "", "", ""],
        ["Mandatory fields must be filled in for every sample, or biosamples.py stops.", "", "", "", "", "", ""],
        ["Recommended and optional fields may be left empty; empty cells are not submitted.", "", "", "", "", "", ""],
        ["Fields listed below but absent from the DATA sheet can be added as extra columns.", "", "", "", "", "", ""],
        ["A '<field> [unit]' column sets the unit for that field. Leave it empty to use", "", "", "", "", "", ""],
        ["the checklist default, which exists only where the checklist offers one unit.", "", "", "", "", "", ""],
        ["", "", "", "", "", "", ""],
        ["isolate, organism and taxon_id are not checklist fields. ENA needs them for", "", "", "", "", "", ""],
        ["every sample, so they are always required.", "", "", "", "", "", ""],
        ["", "", "", "", "", "", ""],
        ["Checklist source: https://www.ebi.ac.uk/ena/browser/view/" + spec["accession"], "", "", "", "", "", ""],
        ["", "", "", "", "", "", ""],
        INFO_HEADER,
    ]

    for name in CORE_COLUMNS:
        rows.append([name, "required (not a checklist field)", "", "",
                     CORE_HELP[name], "sample identification", ""])

    for key in spec["order"]:
        field = spec["fields"][key]
        status = field["status"]
        if _norm(field["label"]) not in in_table:
            status += " (not in the DATA sheet)"
        rows.append([
            field["label"],
            status,
            ", ".join(field["units"]),
            summarise_choices(field["choices"]),
            field["description"],
            field["group"],
            field["name"],
        ])

    return rows


def header_row(columns):
    """DATA header: each field, followed by its unit column where relevant."""
    header, styles = [], []
    for name, status, units in columns:
        header.append(name)
        styles.append(status)
        if units:
            header.append(f"{name} [unit]")
            styles.append("unit")
    return header, styles


def write_xlsx(path, columns, info_rows):
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    header, styles = header_row(columns)

    wb = Workbook()
    data_sheet = wb.active
    data_sheet.title = "DATA"
    data_sheet.append(header)

    for index, (title, style) in enumerate(zip(header, styles), start=1):
        cell = data_sheet.cell(row=1, column=index)
        cell.font = Font(bold=(style != "unit"), italic=(style == "unit"))
        cell.fill = PatternFill("solid", start_color=FILL_BY_STATUS[style],
                                end_color=FILL_BY_STATUS[style])
        cell.alignment = Alignment(horizontal="left", vertical="center")
        data_sheet.column_dimensions[get_column_letter(index)].width = min(
            max(len(title) + 2, 12), 42
        )
    data_sheet.freeze_panes = "A2"

    info_sheet = wb.create_sheet("INFO")
    for row in info_rows:
        info_sheet.append(row)

    # Bold the INFO table header, which sits below the preamble
    for row in info_sheet.iter_rows():
        if [c.value for c in row][:1] == [INFO_HEADER[0]]:
            for cell in row:
                cell.font = Font(bold=True)
            break
    for index, width in enumerate([40, 30, 18, 46, 70, 34, 34], start=1):
        info_sheet.column_dimensions[get_column_letter(index)].width = width

    wb.save(path)


def write_delimited(path, columns, info_rows, separator):
    import csv

    header, _ = header_row(columns)
    with open(path, "w", newline="", encoding="utf-8") as handle:
        csv.writer(handle, delimiter=separator).writerow(header)

    stem, ext = os.path.splitext(path)
    info_path = f"{stem}_INFO{ext}"
    with open(info_path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle, delimiter=separator)
        for row in info_rows:
            writer.writerow(row)
    return info_path


def main():
    parser = argparse.ArgumentParser(
        description="Build a blank sample metadata table from an ENA checklist XML."
    )
    parser.add_argument("--config", default="../config.yaml",
                        help="Path to YAML config file (default: ../config.yaml)")
    parser.add_argument("--checklist", metavar="XML",
                        help="Checklist XML to build the table from "
                             "(default: the 'checklist' key of config.yaml)")
    parser.add_argument("-o", "--output", metavar="TABLE",
                        help="Table to write, .xlsx/.csv/.tsv "
                             "(default: the 'data_biosamples' key of config.yaml)")
    parser.add_argument("--all-fields", action="store_true",
                        help="Include the optional checklist fields too, not just "
                             "the mandatory and recommended ones")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite the output file if it already exists")
    args = parser.parse_args()

    cfg = load_config(args.config)

    checklist_path = args.checklist or cfg.get("checklist")
    if not checklist_path:
        sys.exit(
            "No checklist given. Pass --checklist, or add a 'checklist' key to "
            "config.yaml.\nChecklists can be downloaded from "
            "https://www.ebi.ac.uk/ena/browser/checklists"
        )

    output_path = args.output or cfg.get("data_biosamples")
    if not output_path:
        sys.exit(
            "No output table given. Pass -o, or set 'data_biosamples' in config.yaml."
        )

    extension = os.path.splitext(output_path)[1].lower()
    if extension not in {".xlsx", ".csv", ".tsv", ".tab", ".txt"}:
        sys.exit(
            f"Unsupported output extension '{extension}'. "
            "Use .xlsx, .csv or .tsv/.tab/.txt"
        )

    if os.path.exists(output_path) and not args.force:
        sys.exit(
            f"'{output_path}' already exists, so nothing was written.\n"
            "Filling in a template by hand takes a while, so this script will not "
            "overwrite one.\nEither write to a new name and point config.yaml at it:\n"
            f"    python make_table.py -o my_new_table{extension}\n"
            "or overwrite it deliberately with --force."
        )

    spec = parse_checklist(checklist_path)

    extra_mandatory = cfg.get("extra_mandatory") or []
    if isinstance(extra_mandatory, str):
        extra_mandatory = [extra_mandatory]

    columns = select_fields(spec, all_fields=args.all_fields,
                            extra_mandatory=extra_mandatory)
    info_rows = build_info_rows(spec, columns)

    parent = os.path.dirname(os.path.abspath(output_path))
    os.makedirs(parent, exist_ok=True)

    if extension == ".xlsx":
        write_xlsx(output_path, columns, info_rows)
        info_note = "field descriptions are on the INFO sheet"
    else:
        separator = "," if extension == ".csv" else "\t"
        info_path = write_delimited(output_path, columns, info_rows, separator)
        info_note = f"field descriptions were written to {info_path}"

    counts = {}
    for _, status, _ in columns:
        counts[status] = counts.get(status, 0) + 1
    summary = ", ".join(f"{counts[s]} {s}" for s in
                        ("core", "mandatory", "recommended", "optional")
                        if s in counts)

    header, _ = header_row(columns)
    print(f"{output_path} written: {len(header)} columns ({summary})")
    if not args.all_fields:
        skipped = sum(1 for key in spec["order"]
                      if spec["fields"][key]["status"] == "optional")
        if skipped:
            print(
                f"{skipped} optional field(s) were left out. Add them as extra "
                "columns if you need them, or rerun with --all-fields."
            )
    print(f"Next: fill in one row per sample, {info_note}, then run biosamples.py")


if __name__ == "__main__":
    main()